# Generated by Django 4.2 on 2023-06-05 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_aberto', models.DateTimeField(auto_now_add=True)),
                ('hora_fechado', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
