# Generated by Django 4.2 on 2023-05-17 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlecaixa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novocaixa',
            name='hora_fechado',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
