# Generated by Django 4.2 on 2023-06-07 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlecaixa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
