# Generated by Django 4.2 on 2023-06-14 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlecaixa', '0002_alter_caixa_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
