# Generated by Django 4.2 on 2023-05-19 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlecaixa', '0003_novocaixa_caixa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novocaixa',
            name='caixa',
        ),
    ]
