# Generated by Django 4.2 on 2023-05-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlecaixa', '0004_remove_novocaixa_caixa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novocaixa',
            name='hora_aberto',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='novocaixa',
            name='hora_fechado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
