# Generated by Django 4.2 on 2023-05-03 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adicionarpedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.IntegerField()),
                ('cliente', models.CharField(max_length=50)),
                ('valor', models.IntegerField()),
            ],
        ),
    ]
