# Generated by Django 4.2 on 2023-06-05 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('controlecaixa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem_pedido', models.TextField(choices=[('IFOOD', 'ifood'), ('BALCAO', 'Balcao'), ('TELEFONE', 'Telefone'), ('WHATSAAP', 'WhatSaap')], max_length=50)),
                ('id_ifood', models.CharField(blank=True, max_length=20)),
                ('cliente', models.CharField(max_length=100)),
                ('dinheiro', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=10, null=True)),
                ('cartao_credito', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=10, null=True)),
                ('cartao_debito', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=10, null=True)),
                ('pix', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=10, null=True)),
                ('observacoes', models.CharField(blank=True, max_length=200)),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controlecaixa.caixa')),
            ],
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_despesa', models.CharField(max_length=30)),
                ('nome_motoboy', models.CharField(max_length=50)),
                ('valor_dinheiro', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=10, null=True)),
                ('valor_pix', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=10, null=True)),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controlecaixa.caixa')),
            ],
        ),
    ]
