# Generated by Django 4.2 on 2023-06-06 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despesa',
            name='caixa',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='caixa',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='origem_pedido',
            field=models.TextField(choices=[('IFOOD', 'IFOOD'), ('BALCAO', 'BALCAO'), ('TELEFONE', 'TELEFONE'), ('WHATSAPP', 'WHATSAPP')], max_length=50),
        ),
    ]
