# Generated by Django 4.2 on 2023-05-03 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='adicionarpedido',
        ),
    ]
