# Generated by Django 4.2 on 2023-05-05 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('origem', models.TextField(choices=[('IFOOD', 'Ifood'), ('BALCAO', 'Balcao'), ('TELEFONE', 'Telefone')], default=0, max_length=100)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cliente', models.CharField(max_length=100)),
                ('valor', models.IntegerField()),
                ('pagamento', models.TextField(choices=[('DINHEIRO', 'Dinheiro'), ('CARTAO DE CREDITO', 'Cartao de Credito'), ('CARTAO DE DEBITO', 'Cartao de Debito'), ('PIX', 'PIX'), ('ONLINE', 'Online')], default=0, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='ad_pedido',
        ),
    ]
