# Generated by Django 4.2 on 2023-06-06 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlecaixa', '0001_initial'),
        ('pedidos', '0003_despesa_caixa_pedido_caixa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='caixa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='controlecaixa.caixa'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='caixa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='controlecaixa.caixa'),
        ),
    ]
