# Generated by Django 4.2 on 2023-05-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_novo_pedido_delete_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novo_pedido',
            name='cartao_credito',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='novo_pedido',
            name='cartao_debito',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='novo_pedido',
            name='dinheiro',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='novo_pedido',
            name='pix',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
    ]
