# Generated by Django 4.2 on 2023-06-14 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_alter_despesa_caixa_alter_pedido_caixa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despesa',
            name='caixa',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='caixa',
        ),
    ]
