# Generated by Django 4.2 on 2023-05-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_alter_novo_pedido_cartao_credito_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novo_pedido',
            name='cartao_credito',
            field=models.FloatField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='novo_pedido',
            name='cartao_debito',
            field=models.FloatField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='novo_pedido',
            name='dinheiro',
            field=models.FloatField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='novo_pedido',
            name='pix',
            field=models.FloatField(blank=True, default='0'),
        ),
    ]
