# Generated by Django 4.2 on 2023-05-24 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_alter_novo_pedido_id_ifood'),
    ]

    operations = [
        migrations.AddField(
            model_name='novo_pedido',
            name='total_cartao_credito',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='novo_pedido',
            name='total_cartao_debito',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='novo_pedido',
            name='total_dinheiro',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='novo_pedido',
            name='total_pxi',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
    ]
